import Phaser from 'phaser';

/**
 * Load the tileset spritesheet PNG in Phaser's preload phase.
 * The spritesheet is generated by `bun run build:tileset` from individual tile PNGs.
 */
export function loadTileset(scene: Phaser.Scene): void {
  scene.load.image('tileset', 'assets/tileset.png');
  scene.load.tilemapTiledJSON('map', 'assets/map.json');
}
